name: validation
on: [push, pull_request]

# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read
  # packages: read

env:
  GO111MODULE: "on"
  PROJECTNAME: "extendeddaemonset"
  GO_VERSION: 1.24
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: Install required packages
      uses: mstksg/get-package@4eda30bb5c6ac62c0f3921dd5884b6ef8fc89ab2 # v1.0.0
      with:
        apt-get: mercurial jq build-essential
    - name: Check out code into the Go module directory
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Install tools
      run: |
        make install-tools
    - name: Run build
      run: |
        make manager
    - name: Run unit/control plane tests (fake cluster)
      run: |
        make test
    - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cover.out
        flags: unittests
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.14.10
          - v1.16.9
          - v1.18.4
          - v1.21.1
          - v1.22.12
          - v1.23.12
          - v1.24.11
    steps:
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Install required packages
        uses: mstksg/get-package@4eda30bb5c6ac62c0f3921dd5884b6ef8fc89ab2 # v1.0.0
        with:
          apt-get: mercurial jq build-essential
      - name: Check out code into the Go module directory
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install tools
        run: |
          make install-tools
      - name: Setup kind for e2e - kube ${{ matrix.k8s }}
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          config: test/cluster-kind.yaml
          cluster_name: eds-e2e
          wait: 600s
      - name: Run e2e tests - kube ${{ matrix.k8s }}
        run: |
          export PATH=$PATH:$(pwd)/bin
          kubectl cluster-info --context kind-eds-e2e
          kubectl get pods -n kube-system
          make e2e
